# The usual stuff for RL
# env information
env_cfg:
  env_id: CartPole-v1

# experiment related
exp_cfg:
  seed: 0
  epochs: 10
  steps_per_epoch: 2048
  batch_size: 512
  cpu: 4
  gamma: 0.95
  train_iters: 10
  # model hparams
  hparams:
    hidden_size: [64, 64]

# synonymous with Project in wandb
workspace: "PaperRL" 

# can add more slashes to group more.
exp_name: "ppo-CartPole-v1"